
// Find output of below code 

/*

Error occurred

*/

Promise.reject('Error occurred').catch(err => console.log(err));